#ifndef ERROR_MACROS_HPP
#define ERROR_MACROS_HPP

// Errors
#define ERR_NOORIGIN "409"

#define ERR_NONICKNAMEGIVEN "431"
#define ERR_ERRONEUSNICKNAME "432"
#define ERR_NICKNAMEINUSE "433"

#define ERR_NEEDMOREPARAMS "461"
#define ERR_ALREADYREGISTERED "462"
#define ERR_PASSWDMISMATCH "464"

#endif